### ISSUE TITLE
nightly Windows builds have been failing for a few weeks for lack of disk space

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#122]
see https://scala-ci.typesafe.com/job/scala-2.11.x-release-package-windows/ (last green build was Aug 21)

**Comment by adriaanm** [comment]
See #78

**Comment by SethTisue** [comment]
manually fixed for now by ssh'ing in (https://github.com/scala/scala-jenkins-infra/pull/123) and `rm -rf`ing stuff in /home/tmp. I've self-assigned #78 for later.

before closing, let's make sure https://scala-ci.typesafe.com/job/scala-2.11.x-release-main/275/console succeeds (the disk space thing might have been covering other issues)

**Comment by SethTisue** [comment]
275 failed for a different reason, but https://scala-ci.typesafe.com/job/scala-2.11.x-release-main/277/ passed, so we're good
