### ISSUE TITLE
scala-2.11.x-release-package-windows intermittently fails with "cannot find the file... License.rtf"

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#125]
https://scala-ci.typesafe.com/job/scala-2.11.x-release-package-windows/220/console

**Comment by adriaanm** [comment]
Bizarre -- try rebuilding? I vaguely remember seeing this before.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.11.x-release-package-windows/221/console succeeded, so I guess this is some intermittent problem. Updating issue title.

**Comment by SethTisue** [comment]
haven't seen this in ages
