### ISSUE TITLE
Windows jobs intermittently freeze at `git clean` stage

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#143]
and have to be manually aborted

see e.g. https://scala-ci.typesafe.com/job/scala-2.11.x-release-package-windows/286/console

or https://scala-ci.typesafe.com/job/scala-2.12.x-release-package-windows/146/console

**Comment by adriaanm** [comment]
In principle, this was fixed by #132, but somehow the git config command did not result in a `core.longpaths=true` in gitconfig. For now, I manually ssh'ed and set the config option for both --global and --local (as user jenkins)

**Comment by adriaanm** [comment]
TODO: why does the chef solution not work?

```
bash 'git config' do
  interpreter cygbash
  # without longpaths enabled we have:
  # - known problems with `git clean -fdx` failing
  # - suspected problems with intermittent build failures due to
  #   very long paths to some classfiles
  code "git config --global core.longpaths true"
end
```

**Comment by SethTisue** [comment]
I haven't seen this in months, optimistically closing
