### ISSUE TITLE
Update scala-ci certificate by Jan 13, 2016

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#146]
(Adriaan has a new one, just need to deploy it.)

**Comment by SethTisue** [comment]
@adriaanm not sure what this is about, but it'll be Jan 13 soon

**Comment by adriaanm** [comment]
Yep. I have the new cert. Will be in touch about installing it

**Comment by adriaanm** [comment]
cert updated ![new cert until jan 2019](https://www.dropbox.com/s/wmez4gbz8p86pwc/Screenshot%202016-01-12%2014.27.10.png?dl=1)
