### ISSUE TITLE
build-failed emails not being sent 

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#148]
in this repo we have:

```
templates/default/jobs/scala/integrate/community-build.xml.erb:
      <recipients>adriaan@typesafe.com seth.tisue@typesafe.com</recipients>
templates/default/jobs/scala/release/main.xml.erb:
      <recipients>adriaan@typesafe.com seth.tisue@typesafe.com</recipients>
templates/default/jobs/scala/validate/main.xml.erb:
      <recipients>adriaan@typesafe.com seth.tisue@typesafe.com</recipients>
```

but the only emails I ever get from Jenkins are the community-build ones.

hypothesis: it has to do with whether the job runs on jenkins master, or on a worker. the community build jobs run purely on the workers. but the "main" jobs run on master. perhaps un- or mis-configured mail setup on master?

@adriaanm you never get emails about release-main or validate-main jobs failing, do you? there have been a number of times in the last 6 months where those jobs started failing, and nobody noticed until I happened to spot the failures in the Jenkins UI.

**Comment by SethTisue** [comment]
On jenkins-master, the Jenkins config doesn't have an SMTP server configured. But after `sudo yum install telnet`, I can do `telnet localhost 25` and see an SMTP server running. And after `sudo yum install mail`, I can do `echo "test 1" | mail seth.tisue@typesafe.com` and I receive the email. So everything seems in order. Maybe in Jenkins the mail plugin doesn't default to localhost and I need to explicitly specify it?

I'm more puzzled, actually, why it _does_ work on the worker. I can't find anything where SMTP is configured in Jenkins there. after `sudo apt-get install mailutils` (and choosing the "no configuration" option), trying to send mail from the command line just gives `mail: cannot send message: Process exited with a non-zero status`, and `telnet localhost 25` gives "Connection refused."

so the machine where mail seems to be configured properly isn't sending mail, and the machine where mail seems not to be set up at all, _is_ sending mail!

**Comment by SethTisue** [comment]
here's some relevant headers on one of the mails from the worker.

Notice that Google says they're receiving the mail from 54.67.111.226 which is jenkins-master.

```
Delivered-To: seth.tisue@typesafe.com
Received: by 10.112.126.200 with SMTP id na8csp900332lbb;
        Fri, 18 Dec 2015 02:09:42 -0800 (PST)
X-Received: by 10.67.14.201 with SMTP id fi9mr3887449pad.41.1450433382227;
        Fri, 18 Dec 2015 02:09:42 -0800 (PST)
Return-Path: <adriaan@typesafe.com>
Received: from ip-172-31-3-245.us-west-1.compute.internal (ec2-54-67-111-226.us-west-1.compute.amazonaws.com. [54.67.111.226])
        by mx.google.com with ESMTPS id fm5si23110151pab.89.2015.12.18.02.09.41
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 18 Dec 2015 02:09:42 -0800 (PST)
Received: from ip-172-31-3-245.us-west-1.compute.internal (localhost [127.0.0.1])
    by ip-172-31-3-245.us-west-1.compute.internal (8.14.4/8.14.4) with ESMTP id tBIA9fjw016142;
    Fri, 18 Dec 2015 10:09:41 GMT
Message-ID: <1628740267.694.1450433381537.JavaMail.jenkins@ip-172-31-3-245>
```

**Comment by SethTisue** [comment]
maybe I've been barking up all the wrong trees here and Jenkins isn't even attempting to send the mail in the first place.

if you look at the configuration for https://scala-ci.typesafe.com/job/scala-2.11.x-release-main/ the post-build action to send mail is there, but here's the end of a failed community build log:

```
Build step 'Execute shell' marked build as failure
Sending e-mails to: adriaan@typesafe.com seth.tisue@typesafe.com
Notifying endpoint 'HTTP:http://scala-ci.typesafe.com:8888/jenkins'
Finished: FAILURE
```

while here's the end of a failed release-main log:

```
scala-2.11.x-release-smoketest [265] scala/scala-dist-smoketest#2.11.x completed  : FAILURE
Notifying endpoint 'HTTP:http://scala-ci.typesafe.com:8888/jenkins'
Finished: FAILURE
```

hypothesis: perhaps aggregate "build flow" type jobs simply don't send emails?

**Comment by SethTisue** [comment]
the existence of https://issues.jenkins-ci.org/browse/JENKINS-15575 implies that post-build actions certainly _should_ run — they used not to, but it was fixed back in 2012. that includes emails: https://issues.jenkins-ci.org/browse/JENKINS-13521

**Comment by SethTisue** [comment]
aha, here we go. this is a known, open bug: https://issues.jenkins-ci.org/browse/JENKINS-29595 . ah, that welcome "I'm not stupid or crazy" sensation :-)

the workaround is to enable "Flow run needs a workspace". I will try that.

**Comment by SethTisue** [comment]
test release-main run with `<buildNeedsWorkspace>true</buildNeedsWorkspace>`: https://scala-ci.typesafe.com/job/scala-2.11.x-release-main/380/console (will take a few hours, and should fail because of https://github.com/scala/scala-dev/issues/69)

the cookbook from the issue-148 branch in my fork is now in production for testing, so if it ends up not working, I'll need to revert that.

**Comment by adriaanm** [comment]
Thanks for machete-ing your way through the jungle of jenkins -- glad you made it back sane & alive!

**Comment by adriaanm** [comment]
Hopefully we will be victorious in generating more emails.

**Comment by adriaanm** [comment]
Yay!
