### ISSUE TITLE
bring Jenkins into the glorious year of 2016

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#160]
our Jenkins version is pale and rheumy eyed. and has known security holes.

@adriaanm says "the upgrade should happen with chef, by changing the jenkins version number... 
i suppose we can just use the latest version and poke around a bit to make sure nothing is broken... "we had pinned the version because java 7 is now required.. all nodes should have java 8 installed now, i think... i'm not sure about the windows node"

```
override['jenkins']['master']['version']  = '1.611'
```

**Comment by adriaanm** [comment]
done via https://github.com/scala/scala-jenkins-infra/pull/171-- the glorious new jenkins version is 1.658, not 2.0, sadly
