### ISSUE TITLE
Please give me more access rights

### ISSUE THREAD

**Issue by smarter** [scala/scala-jenkins-infra#162]
cf https://gitter.im/lampepfl/dotty?at=56cc8293631af87d5c4534d5

I (and @DarkDimius too probably) would like the ability to abort Jenkins builds, and maybe also access to stuff like https://scala-ci.typesafe.com/job/dotty-master-validate-partest/configure

**Comment by SethTisue** [comment]
> smarter changed the title from Give me more access rights to Please give me more access rights

:-)

**Comment by SethTisue** [comment]
#165 has been deployed via chef-client. if it doesn't fix this for you let me know. (perhaps Jenkins needs to be restarted)

**Comment by smarter** [comment]
Thanks, looks like it worked!
