### ISSUE TITLE
artifactory upgrade 

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#170]
We need the ivy pattern for sbt and that isn't available in oss until artifactory 4.6. We need that pattern to consolidate all repos needed for community build.

**Comment by SethTisue** [comment]
(the motivation here is to reduce the time the community build takes, currently 10+ hours, much of it spent resolving. @InTheNow reports running Artifactory locally and having the community build finish in less than 3 hours; we ought to be able to get in that same ballpark)

**Comment by ghost** [comment]
Hi,

From the GUI - "You are running Artifactory version 4.0.2",  so it might be that just consolidating your repositories on artifactory will suffice.

**Comment by adriaanm** [comment]
thanks -- I've upgraded artifactory in #171, will look into that virtual repo tomorrow, now that we have the right repo layouts available to us

**Comment by adriaanm** [comment]
@InTheNow, would you have the consolidated repo config you're using readily available for sharing?

**Comment by ghost** [comment]
> would you have the consolidated repo config you're using readily available for sharing?

I hope to have a docker image ready for the whole thing today.... let's see

**Comment by adriaanm** [comment]
Thanks for the pointers! I went ahead and implemented your suggestions. I had to upgrade our artifactory, which triggered a whole avalanche of upgrades, but we're all on Java 8 and using caching.
