### ISSUE TITLE
move artifactory config under source control

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#172]
right now it's all configured in the UI (except for the vhost connector config), hoping nothing is accidentally lost...

**Comment by adriaanm** [comment]
Here's the current dump: https://gist.github.com/adriaanm/057ced9b739466d87a09ed24a4367bd5

**Comment by SethTisue** [comment]
newer dump: https://gist.github.com/SethTisue/4ef883260582d06f29ea3fb065f6fde9

**Comment by SethTisue** [comment]
@adriaanm is there a current snapshot?

**Comment by adriaanm** [comment]
there is, indirectly -- in the full snapshot of the ec2 instance's volume.

**Comment by SethTisue** [comment]
snapshot: https://gist.github.com/SethTisue/0a3238add54afcc4a79c37497939f211

**Comment by SethTisue** [comment]
fresh snapshot: https://gist.github.com/SethTisue/81b13979a80840bc6260a07cc8679879

I added the same resolver that I added in https://github.com/scala/community-builds/pull/808

it's unfortunate that we have two basically the same, yet somewhat divergent configs (the one on scala-ci, and the one for local usage), but oh well, neither changes very often

**Comment by SethTisue** [comment]
Adriaan upgraded Artifactory to 6.3.0 (in December I think it was). current config is https://gist.github.com/SethTisue/d07fbd5be4adcdc6b5a2f2e6ffb37daf

**Comment by SethTisue** [comment]
our Artifactory is on 6.11.3 these days, config snapshot https://gist.github.com/SethTisue/41db3da48f3989b7b8d35c4f7c1c59e8

**Comment by SethTisue** [comment]
I made some small changes for https://github.com/scala/community-builds/pull/969

new config: https://gist.github.com/SethTisue/c9622908888de62432af0bd604c03656

**Comment by SethTisue** [comment]
these days pretty much everybody just publishes their sbt plugins to Maven Central (or, until recently, to repo.scala-sbt.org) and it's exceedingly rare we ever need to add a resolver or otherwise adjust the config anymore
