### ISSUE TITLE
Make it possible to use early access builds of OpenJDK

### ISSUE THREAD

**Issue by retronym** [scala/scala-jenkins-infra#174]
Motivation is to start testing with JDK9, and to be able to run our community build with betas of JDK8 minor releases.

There is an Ubuntu package that downloads and installs JDK9. This appears to be actively maintained. It requires `add-apt-repository ppa:webupd8team/java`.

https://launchpad.net/~webupd8team/+archive/ubuntu/java
https://launchpad.net/~webupd8team/+archive/ubuntu/java/+packages

Alternatively, we could grab a binary ourselves:

```
curl -L --verbose https://home.java.net/download/java/jdk9/archive/115/binaries/jdk-9-ea+115_linux-x86_bin.tar.gz
```

And make that available on the system.

Chef's `java` cookbook supports an install from a URL, too. See "Production Deployment with Oracle Java" on https://supermarket.chef.io/cookbooks/java.

I've no idea which way to go, so /assign to @adriaanm.

**Comment by adriaanm** [comment]
The java cookbook assumes a single JDK, so it's mostly a matter of getting the packages installed with another recipe. The workers are on ubuntu, so that should be easy. The chef recipe for install java packages is https://github.com/scala/scala-jenkins-infra/blob/master/recipes/_java_packages.rb

I'll see about adding the repo and install the package some time after m5

**Comment by retronym** [comment]
For now, I've manually installed JDK 9 ea on the behemoths in `$HOME/usr/lib/jvm/jdk-9`.

I've also exported `rt.jar` into `$JAVA_HOME/scala-ext`. With snapshot builds of SBT, or with the yet to be released 0.13.14, this enables:

```
% export JAVA_HOME=$HOME/usr/lib/jvm/jdk-9

% export PATH=$JAVA_HOME/bin:$PATH

% java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+156)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+156, mixed mode)

% sbt -Dscala.ext.dirs=$JAVA_HOME/scala-ext
[info] Loading global plugins from /home/jenkins/.sbt/0.13/plugins
[info] Loading project definition from /home/jenkins/code/scratch/project
[info] Set current project to scratch (in build file:/home/jenkins/code/scratch/)
> sbtVersion
[info] 0.13.14-b646662
> eval System.getProperty("java.specification.version")
[info] ans: String = 9
> consoleQuick
[info] Starting scala interpreter...
[info]
Welcome to Scala version 2.10.6 (Java HotSpot(TM) 64-Bit Server VM, Java 9-ea).
Type in expressions to have them evaluated.
Type :help for more information.

scala> System.getProperty("java.specification.version")
res0: String = 9
```

**Comment by SethTisue** [comment]
we have Java 9 now. we aren't using Chef anymore, manual JDK installs are fine.

**Comment by SethTisue** [comment]
This has continued to be fine. Sample ticket showing what's involved with upgrading: https://github.com/scala/community-build/issues/1492
