### ISSUE TITLE
Jenkins isn't validating PR 5284, hey Scabot wtf?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#185]
why is https://github.com/scala/scala/pull/5284#issuecomment-242813650 wedged?

not all PR validation is wedged; e.g. https://github.com/scala/scala/pull/5360, created a few minutes ago, is validating

so maybe it's Scabot's fault?

**Comment by SethTisue** [comment]
after trying `/sync` on the PR, `ssh jenkins-master` + `less ~scabot/logs/current` shows:

```
[ERROR] [08/26/2016 23:41:43.971] [application-akka.actor.default-dispatcher-40625] [akka://application/user/github/scala-scala/5284] FAILED synchBuildStatuses(CombiCommitStatus(pending,af320d016549318138a9844a6f7e2ad67eadcc14,List(CommitStatus(pending,Some(validate-main),Some([?] Pending. ),Some()), CommitStatus(success,Some(cla),Some(@milessabin signed the Scala CLA. Thanks!),Some(https://www.lightbend.com/contribute/cla/scala/check/milessabin))),2)): spray.httpx.PipelineException: Object is missing required member 'building'
```

**Comment by SethTisue** [comment]
Jenkins hates @milessabin — now https://github.com/scala/scala/pull/5346 is affected too

**Comment by adriaanm** [comment]
I think it has something to do with jenkins having a different json format for pending jobs or jobs that are initializing or something.

**Comment by milessabin** [comment]
:scream_cat:

**Comment by SethTisue** [comment]
@milessabin (I haven't forgotten you, just a bit overloaded with RC1 stuff right now)

**Comment by milessabin** [comment]
No worries :-)

**Comment by SethTisue** [comment]
I didn't fix anything but 1) those PRs seem fine now, and 2) I haven't seen it happen on any other PRs in the last couple months

so I'm leaving this open, but not planning to investigate unless it starts actively causing trouble again

**Comment by adriaanm** [comment]
Then I suggest we close it and reopen if it needed.
