### ISSUE TITLE
improve error message when publish-core fails

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#196]
We should improve the error message (there's an attempt at that here: https://github.com/scala/scala-jenkins-infra/blob/master/templates/default/jobs/scala/validate/main.xml.erb#L27)

see https://github.com/scala/scala/pull/5478#issuecomment-256069149 for an example of the confusing error

**Comment by SethTisue** [comment]
PR validation is moving to Travis-CI
