### ISSUE TITLE
push-to-deploy using chef zero and secret management

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#2]
Move away from hosted chef and client-server setup. It's much nicer to have everything versioned in git (right now, we need to go the the chef.io website to find out which version of cookbooks are used). For secret management, we could use https://vaultproject.io/ (via http://sirupsen.com/production-docker/#secrets). We still need some kind of search to discover nodes, though maybe that's kind of overkill? 
- [x] experiment with chef-solo (--> it's not a solution)
- [x] ~~replacement for chef vault?~~ (nope, it needs chef server)
- [ ] push to deploy instead of knife cookbook upload?

**Comment by adriaanm** [comment]
See also https://www.chef.io/blog/2014/06/24/from-solo-to-zero-migrating-to-chef-client-local-mode/.

**Comment by SethTisue** [comment]
bye bye Chef!
