### ISSUE TITLE
don't overwrite artifacts in http://private-repo.typesafe.com/typesafe/simple/scala-release-temp/

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#20]
[scala-2.11.x-release-package-windows](https://scala-ci.typesafe.com/job/scala-2.11.x-release-package-windows/5/) and [scala-2.11.x-release-package-unix](https://scala-ci.typesafe.com/job/scala-2.11.x-release-package-unix/4/) both downloaded http://private-repo.typesafe.com/typesafe/simple/scala-release-temp/org/scala-lang/scala-dist/2.11.6-7b5998a-nightly/, where the -unix job's workspace has the jar with a doc/ folder, the windows one has the later(??) version, which lacks it.

An [earlier -windows job](https://scala-ci.typesafe.com/job/scala-2.11.x-release-package-windows/3) got the right jar, it seems....

**Comment by SethTisue** [comment]
release jobs have moved to Travis-CI+Appveyor
