### ISSUE TITLE
#206 removed CLA checking from Dotty

### ISSUE THREAD

**Issue by felixmulder** [scala/scala-jenkins-infra#207]
Hello again - as continued from Gitter:

PR #206 removed both the validate jobs and the CLA checking, but we want to keep the CLA checking - pretty please! :smiley:

**Comment by SethTisue** [comment]
are you sure? on e.g. a very recent PR like https://github.com/lampepfl/dotty/pull/1796 I see what appears to be a successful CLA check?

**Comment by SethTisue** [comment]
Oh, is that because you re-enabled the webhook?

**Comment by SethTisue** [comment]
let's continue on #208
