### ISSUE TITLE
chara's hostkey changed?

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#210]
https://scala-ci.typesafe.com/job/scala-2.11.x-release-website-archives/529/console

**Comment by SethTisue** [comment]
while you're up in this chara stuff, you might see if you can get scala-2.13.x-release-website-archives working; it's (I think) the last thing preventing scala-2.13.x-release-main from being green

**Comment by SethTisue** [comment]
let's loop in @fsalvi — Fabien, did something change on chara that you're aware of?

**Comment by fsalvi** [comment]
Yes, I reinstalled chara.epfl.ch to a new machine yesterday, and the host key changed.
Let me know if there's anything I can do on my side...

**Comment by adriaanm** [comment]
that job should be ok now, was missing a `mkdir -p "$archivesDir"`
