### ISSUE TITLE
zombie Dotty jobs rise from the dead, stagger, groan

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#215]
where is this coming from?

<img width="392" alt="screen shot 2017-02-02 at 8 50 20 am" src="https://cloud.githubusercontent.com/assets/161079/22556517/a845643a-e924-11e6-8230-9f70f736b8ae.png">

**Comment by SethTisue** [comment]
is this some side effect of the benchmarking work that's been happening recently?

or maybe the jobs were never fully killed off and we just didn't notice until now?

**Comment by lrytz** [comment]
i don't see any way this could be caused by the benchmarking work

**Comment by SethTisue** [comment]
deleted the jobs via web UI at https://scala-ci.typesafe.com/view/All/, hopefully that's the last of it then

**Comment by DarkDimius** [comment]
Weren't they still there to check the CLA for dotty? 
https://github.com/scala/scala-jenkins-infra/pull/208

**Comment by SethTisue** [comment]
I don't think so. #206 expunged everything related to Dotty.

**Comment by DarkDimius** [comment]
#208 reintroduced dotty after #206 removed it.

**Comment by SethTisue** [comment]
#208 was not merged
