### ISSUE TITLE
dump environment relevant to reproducing build locally

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#23]
It should be easy to figure out how to retry PR validation failures, see e.g.: https://github.com/scala/scala/pull/4284#issuecomment-72524262

**Comment by ms-tg** [comment]
:+1:

**Comment by SethTisue** [comment]
hopefully this will get simpler in the course of https://github.com/scala/scala-dev/issues/507

**Comment by SethTisue** [comment]
the Travis-CI and GitHub Actions builds are so much simpler — just a few commands each — that this basically isn't an issue anymore. Jenkins still uses the more complicated scripts but that's just a historical accident
