### ISSUE TITLE
upgrade to newer version of Node

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#233]
this will probably resolve the Scala.js InteroperabilityTest failures we're seeing in the community build

**Comment by SethTisue** [comment]
the original PR enabling node was https://github.com/scala/scala-jenkins-infra/pull/187

on worker-behemoth-1:

```
ubuntu@ip-172-31-4-164:~$ nodejs --version
v4.2.6
ubuntu@ip-172-31-4-164:~$ sudo apt-get update
...
ubuntu@ip-172-31-4-164:~$ sudo apt-get upgrade nodejs
...
nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.1).
```

**Comment by SethTisue** [comment]
there is a newer version of the nodejs cookbook that supports additional installation methods: https://supermarket.chef.io/cookbooks/nodejs/versions/3.0.0

looks like we'd need "Install node from official prebuilt binaries" since apt doesn't have something newer

**Comment by SethTisue** [comment]
hmm, or we could leave the cookbook alone and just use the instructions at https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions to upgrade the workers. after all there's currently nothing in this repo that actually specifies the node version, so the status quo is already “whatever apt-get got us"

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by SethTisue** [comment]
I ran the above commands on both behemoths. https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/681/consoleFull shows that this fixed Scala.js 🎉

**Comment by sjrd** [comment]
Thanks @SethTisue :)
