### ISSUE TITLE
initiate a policy of always logging any manual actions taken on the nodes

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#234]
e.g. installing software it's too painful to go through Chef for, or whatever

**Comment by adriaanm** [comment]
https://github.com/scala/scala-jenkins-infra/blob/master/automationPending.md

**Comment by SethTisue** [comment]
fyi @retronym

**Comment by SethTisue** [comment]
added the new policy to the maintenance document: 945332428afa80e67a7f472d13718cca4a3a476a

**Comment by retronym** [comment]
Roger that, I've noted that alt-JDK installation is has been done manually.
