### ISSUE TITLE
jenkins-master is very low on disk space currently

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#241]
attn @adriaanm https://scala-ci.typesafe.com/computer/ shows only 3.47 GB free

(normally I'd of course deal with this myself, but I haven't studied the new setup yet)

**Comment by SethTisue** [comment]
2.72 GB free

**Comment by adriaanm** [comment]
I deleted jobs that hadn't been accessed since over 6 months: ` find -type d -atime +180 -maxdepth 3  | grep -P "builds/\d+$" | xargs rm -rf`. Now we have 50G available again. I'll also configure CI jobs to only retain up to 6 months from now on.

**Comment by SethTisue** [comment]
take that, archaeologists!
