### ISSUE TITLE
Scala 2.11 community build needs JDK 6 installed

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#242]
as seen at https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/950/

```
+ jvmSelect oracle 6
+ jvmFlavor=oracle
+ jvmMajorVersion=6
+ jvmRoot=/usr/lib/jvm/
++ find -L /usr/lib/jvm/ -name javac -type f -path '*6*oracle*'
+ eligibleCmds=
+ unset jdkHome
+ '[' -d '' ']'
+ echo 'Failed to locate oracle Java 6 in /usr/lib/jvm/, containing:'
Failed to locate oracle Java 6 in /usr/lib/jvm/, containing:
+ find /usr/lib/jvm/ -name java
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
/usr/lib/jvm/java-8-openjdk-amd64/bin/java
/usr/lib/jvm/java-9-openjdk-amd64/bin/java
+ exit 1
Build step 'Execute shell' marked build as failure
```

this is not urgent. there is no action in 2.11 land currently, and we have the 2.11.x-jdk8 build, *and* if we need to do a JDK 6 run for QA purposes we can always just do it on a laptop or whatever

**Comment by SethTisue** [comment]
in the meantime, some tips for running locally on MacOS:

* `brew cask install java6`
* `run.sh` does not check the JDK version, so be sure and:
    * `export JAVA_HOME=$(/usr/libexec/java_home -v 1.6)`
* if you get "java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"
    * `sudo rm /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/security/cacerts`
    * `sudo ln -s  /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/security/cacerts /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/security/cacerts`

UPDATE: https://github.com/SethTisue/community-builds/tree/2.11.x-jdk6-local-run has some further tweaks I'm using. (Including using a local Artifactory, it's agonizingly slow without one.)

**Comment by SethTisue** [comment]
@adriaanm I can ssh to the behemoths now, but I can't `apt-get install` because I can't `sudo` that voodoo that I do:

```
[sudo] password for jenkins:
```

**Comment by adriaanm** [comment]
`jenkins` can't `sudo`, that would be a huge security hole. You should log in as the `admin` user.

**Comment by adriaanm** [comment]
(no `sudo make me a sandwich` for you, jenkins)

**Comment by adriaanm** [comment]
regarding installing Java 6, I don't know how to get there. Oracle's distro requires a license. Old versions of OpenJDK  are hard to install on modern debian.

**Comment by SethTisue** [comment]
> You should log in as the admin user 

works, thanks.

> regarding installing Java 6, I don't know how to get there. Oracle's distro requires a license

uh, how is that even possible? it was free before, we had it installed before. confused

**Comment by SethTisue** [comment]
(it isn't urgent for community build reasons, but we need to be able to roll 2.11.13 if we must)

**Comment by SethTisue** [comment]
also what if we need to roll 2.11.13 (or, god forbid, 2.10.8) because of some security hole or something?

**Comment by SethTisue** [comment]
I now finally have a fully green 2.11.x/JDK6 build running locally on my Mac (see remarks above at https://github.com/scala/scala-jenkins-infra/issues/242#issuecomment-365815533), and I have an automated reminder that reminds me to run it every so often.

I think that's fine for now. We can cross the 2.11.13 bridge if we ever come to it.

**Comment by SethTisue** [comment]
having trouble letting this go...

reference on JDK 6 no longer being available via `sudo add-apt-repository ppa:webupd8team/java` plus `sudo apt-get install oracle-java6-installer` like used to work: http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html

however Java 6 Update 45 does remain available from http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase6-419409.html

**Comment by SethTisue** [comment]
manually installed Java 6 Update 45 into `/usr/lib/jvm`

`jvmSelect` finds it as long as you specify the Java "flavor" as `j` (I thought `jdk` would work and it didn't so I tried `j` on a hunch and bingo)

changed the 2.11 job configuration to do that, and to run `@daily`

wiped out workspace, just in case

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/955/

**Comment by SethTisue** [comment]
green now at https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/957/ (last piece was https://github.com/SethTisue/browse/commit/7852a85cc658c4bb89fea89db0fe49c3ee0cf09d)
