### ISSUE TITLE
Community builds need `cloc` installed on behemoths

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#244]
via, like, you know, `sudo apt-get install cloc` or whatever

@adriaanm can you either do this, or help me do it myself? I don't know how to ssh to the behemoths anymore. I'll need to know eventually, you can judge whether you'd rather walk me through it now, or just do the installation and we'll come back to the setup/training/documentation when fewer things are exploding

**Comment by adriaanm** [comment]
Done: ` for i in jenkins-worker-behemoth-{1,2,3}; do ssh $i sudo apt-get install -y cloc; done`

**Comment by SethTisue** [comment]
thanks! (and also, I can ssh to both master and the behemoths now)
