### ISSUE TITLE
move 2.13 community build to behemoth 3

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#245]
all community builds should remain pegged to particular behemoths, so that the stuff dbuild caches in the workspace (mainly, but also in `~/.dbuild`) only gets cached once. this matters both so the runs finish faster, and to avoid excessive disk usage.

currently we have both 2.11 builds on behemoth 1 and the 2.12 & 2.13 builds on behemoth 2

now that our mighty army of behemoths is three strong (striking fear into the hearts of our enemies; they tremble at what would happen should Scala ever acquire a fourth behemoth) we should move the 2.13 build to behemoth 3, to reduce contention on behemoth 2.

**Comment by SethTisue** [comment]
@adriaanm I used to know how to do this with Chef. what's the drill these days?

**Comment by adriaanm** [comment]
update the config through the UI and then do `rsync -av --existing jenkins@scala-ci.typesafe.com:~/ roles/jenkins/files` into your check out. Then add and commit with git.

**Comment by SethTisue** [comment]
this worked: `rsync -av --progress --existing admin@scala-ci.typesafe.com:/var/lib/jenkins/ roles/jenkins/files`

**Comment by SethTisue** [comment]
closing since the change is live and on the assumption Adriaan will merge #247

**Comment by SethTisue** [comment]
I blew away the old workspace on behemoth 2

and there is now a behemoth 3 run in progress at https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/956/
