### ISSUE TITLE
Configure validate-test job to archive JUnit test reports

### ISSUE THREAD

**Issue by retronym** [scala/scala-jenkins-infra#25]
From the old validator:

![image](https://cloud.githubusercontent.com/assets/65551/6011822/0510fde2-ab8c-11e4-8451-7b0c8fc12bf8.png)

We could also store the `test/flles/**/*.log` files to show the actual results of partest when it differs from the check file.

**Comment by adriaanm** [comment]
Fixed by 94eb292a4d9491b7d4dbf5d51e51f0739b4577b8
