### ISSUE TITLE
Error upload to server

### ISSUE THREAD

**Issue by dediwah** [scala/scala-jenkins-infra#255]
I Have problem as follow :

Array ([0] =># [1] => # There is insufficient memory for the Java Runtime Environment to continue. [2] => # Native memory allocation (mmap) failed to map 2555904 bytes for committing reserved memory. [3] => # An error report file with more information is saved as: [4] => # /tmp/hs_err_pid5636.log ) 1 

please help me

**Comment by SethTisue** [comment]
This repo isn't relevant to your problem.

Are you using Scala? If so, see https://www.scala-lang.org/community/ for ideas on where to seek help with it. https://users.scala-lang.org and https://gitter.im/scala/scala are typical choices.
