### ISSUE TITLE
Upgrade our Jenkins

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#256]
version has fallen behind

our version: 2.231 (Apr 14)
latest version: 2.240 (Jun 8)

changelog at https://www.jenkins.io/changelog/ — nothing jumps out at me as concerning

there are also some plugins that a system alert is telling us we should upgrade (Script Security Plugin, Copy Artifact Plugin, Credentials Binding Plugin)

finally, there is an alert about a legacy API token, used by the scala-jenkins user. I don't recall if that user actually is connected to anything or whether it's leftover from some previous era. but it does say "Days since last use: 0" so maybe scabot is using it, except in the Scabot repo `git grep scala-jenkins` shows nothing, but in this repo there is stuff about in `doc/genesis.md` so it probably is used

**Comment by SethTisue** [comment]
plugins upgraded (and Jenkins restarted via https://scala-ci.typesafe.com/safeRestart), but "Copy Artifact" is [asking](https://scala-ci.typesafe.com/manage) for further changes: "Copy Artifact is running in Migration mode. For improved security you should switch to Production mode."

**Comment by SethTisue** [comment]
I didn't find anywhere where we're using Copy Artifact except perhaps in the 2.12.x-release-main job which is disabled anyway, so I went ahead and (via https://scala-ci.typesafe.com/configureSecurity/) switched the plugin to Production mode

**Comment by SethTisue** [comment]
now as for upgrading Jenkins itself, there is no auto-upgrade button on https://scala-ci.typesafe.com/manage. in my now-years-old memory of doing this last, you just swapped in a new `jenkins.war` on the server and restarted, but it doesn't seem to work that way anymore

looks like `systemctl` runs `/etc/init.d/jenkins` ... and, oh, `/etc/default/jenkins` sets `JENKINS_WAR` to `/usr/share/jenkins/jenkins.war`, found you you pesky WAR

oh, I guess I could have found it more easily via "Manage Jenkins -> System Information", oh well

so:

```
cd /usr/share/jenkins
sudo chgrp jenkins jenkins.war
sudo chmod g+w jenkins.war
```

and restarted Jenkins, but the auto-upgrade button didn't appear

I guess I'll swap the new JAR in manually.

for caution's sake, I undid the above permissions changes:

```
sudo chown root:root jenkins.war
sudo chmod 644 jenkins.war
```

and then:

```
sudo cp -p jenkins.war jenkins.war-old
sudo curl -O -L 'http://updates.jenkins-ci.org/download/war/2.240/jenkins.war'
```

and restart again, and Bob's your uncle!

**Comment by SethTisue** [comment]
so that just leaves the question of the legacy API token, now. I'll look into that another day (but soon)

**Comment by lrytz** [comment]
I thought jenkins auto-updates through debian's unattended upgrades (https://pkg.jenkins.io/debian/)

**Comment by SethTisue** [comment]
oh? well, it hadn't updated in close to three months

I ran `sudo apt-get update` and this seems to be why:

```
Err:8 https://pkg.jenkins.io/debian binary/ Release.gpg  
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FCEF32E745F2C3D5
Fetched 833 B in 0s (1,431 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://pkg.jenkins.io/debian binary/ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FCEF32E745F2C3D5
W: Failed to fetch https://pkg.jenkins.io/debian/binary/Release.gpg  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FCEF32E745F2C3D5
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

and aha, at https://pkg.jenkins.io/debian/ it says `The gpg key use to sign our packages has been updated on 16th of April 2020`

as that page suggests, I ran `wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -` and then after that,`sudo apt-get install jenkins` (you use `install` for both initial installation and upgrades) succeeded :+1:, thanks @lrytz for the pointer

for good measure I did https://scala-ci.typesafe.com/safeRestart one more time

**Comment by SethTisue** [comment]
> I thought jenkins auto-updates through debian's unattended upgrades (https://pkg.jenkins.io/debian/)

this is working again now — the upgrade to 2.241 happened by itself

**Comment by SethTisue** [comment]
I'm going to close this despite not having dealt with the legacy-API-token thing, I'm guessing it's not important
