### ISSUE TITLE
Decommission Jenkins Windows workers

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#260]
there is no further need for https://scala-ci.typesafe.com/computer/jenkins-worker-publish/ , now that https://github.com/scala/scala/pull/9496 has landed and https://github.com/scala/scala/pull/9591 is about to land

I have already disabled https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-windows/ and https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-windows/

@lrytz I've never touched the EC2 side of the Jenkins stuff. is this something you could handle...? (I'm not even certain there is anything that needs to be done. if Jenkins no longer ever wakes up the instance, perhaps the cost drops to $0.00 and that's the end of it? no clue.)

**Comment by lrytz** [comment]
I can remove the instances eventually. There's a tiny cost for keeping the EBS volume around, but overall costs are dominated by compute time.

**Comment by SethTisue** [comment]
@lrytz maybe time to pull the trigger on this? I worry about security when old stuff just hangs around indefinitely

**Comment by lrytz** [comment]
The only thing I could possibly imagine is if we would need another 2.11 release. But restoring that ability would probably be just as hard as backporting the current release infra from 2.12/2.13 to 2.11?

**Comment by SethTisue** [comment]
At present I’m only proposing decommissioning the Windows worker; 2.11 releases were done by the Ubuntu worker.

**Comment by lrytz** [comment]
I *think* (not sure though) the windows machine was used for building the msi (https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-release-package-windows/)

**Comment by SethTisue** [comment]
Ah, I stand corrected (or perhaps-corrected).

If we had to do another 2.11 release but just leave out the MSI, that wouldn't exactly be the end of the world.

But perhaps it's better to just leave this alone, then. Shall I close the ticket?

**Comment by lrytz** [comment]
I think we can leave things in place as they are for now, until the moment when we actually have a reason to change them (maybe when we get rid of our jenkins). The Windows machines are never actually running, so I don't see a big risk.

**Comment by lrytz** [comment]
i removed the windows and the linux-publish vms.
