### ISSUE TITLE
admin rights for github group scala core team

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#29]
right now, admin usernames are listed in `default['master']['github']['adminUserNames']  = 'adriaanm,chef,scala-jenkins'` at https://github.com/scala/scala-jenkins-infra/blob/master/attributes/master.rb#L14

can the github oauth plugin suck this data in from github rights?

**Comment by adriaanm** [comment]
Add @lrytz and @retronym to this group

**Comment by lrytz** [comment]
done manually in #42 (not via github rights)
