### ISSUE TITLE
tweak parallelism for executors / partest threads

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#33]
right now, we seem pretty ok: 
- 4 parallel test runs run in 125 min, 
- 2 parallel: 76 min, 
- 1 single job: 50 min

![screenshot](https://www.dropbox.com/s/ml928cftgm4koc3/Screenshot%202015-02-10%2023.22.07.png?dl=1)

**Comment by lrytz** [comment]
thanks for checking!

**Comment by SethTisue** [comment]
I'm not aware of any current shortcomings in this area, and anyway pretty soon Jenkins won't be doing much but the community build and the compiler benchmarks
