### ISSUE TITLE
"JVM is terminating. Shutting down Winstone"

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#34]
[This job](https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/244/console) just stopped with no apparent reason.

The log on jenkins-master says:

```
Feb 16 18:05:07 ip-172-31-2-59 [jenkins]: INFO: JVM is terminating. Shutting down Winstone
```

**Comment by adriaanm** [comment]
OOM ?

http://jenkins-ci.361315.n4.nabble.com/Jenkins-JVM-crashes-after-few-minutes-after-start-td4417465.html?

**Comment by adriaanm** [comment]
We already run under

```
cd /var/lib/jenkins
touch jenkins.start
exec chpst -u jenkins -U jenkins \
  env HOME=/var/lib/jenkins \
  JENKINS_HOME=/var/lib/jenkins \
  java -server -Xmx4G -XX:MaxPermSize=512M -XX:+HeapDumpOnOutOfMemoryError -jar jenkins.war \
  --httpPort=8080 \
  --httpListenAddress=127.0.0.1 \
```

and no hprof memory dumps were found. CPU usage was much higher than usual according to EC2 monitoring, but that's all I have...

**Comment by som-snytt** [comment]
Maybe it's terminated from a browser console due to a javascript bug. Or a Jenkins virus!

**Comment by retronym** [comment]
That message is logged in a [JVM shutdown hook](https://github.com/jenkinsci/winstone/commit/13e0d9b845353b5aecf3d319ddb0d0c642be771b)

If we keep seeing this, we could start that JVM with a custom java agent that logs a stack trace when `System.exit` is called. I can't think of a more straight forward way to diagnose this.

**Comment by adriaanm** [comment]
Closing because we haven't seen this since.
