### ISSUE TITLE
release/finalize/publish job

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#41]
consume release.properties artifact created upstream (TODO) by
- integrate/bootstrap persists 
  - sonatype staging repo id (sonaStagingRepoIds)
  - sha of scala/scala (scalaSha)
- release/package/unix persists 
  - sha of scala/scala (scalaDistSha)

This job is run in dry-run mode at end of staging job flow, and can be rebuilt to complete the release process once staging was tested by community.

When re-run under doRelease=1, it runs (example values for properties from 2.10.5 release):

```
repo_user="scala"
version="2.10.5"
scalaDistSha="0ec20a73fac8578ec1e469ff0a8c59726a2f0553"
scalaSha="88c5407613a3d8281b9b50c4bb110849a0149a97"
sonaStagingRepoIds="orgscala-lang-1186"

cd ~/git/scala-dist
git fetch https://github.com/$repo_user/scala-dist.git
git tag -s -m "Scala $version" v$version $scalaDistSha
git push https://github.com/$repo_user/scala-dist.git v$version

cd ~/git/scala
git fetch https://github.com/$repo_user/scala.git
git tag -s -m "Scala $version" v$version $scalaSha
git push https://github.com/$repo_user/scala.git v$version

for repo in $sonaStagingRepoIds; do st_stagingRepoPromote $repo; done 
```

and notifies scala-internals

**Comment by SethTisue** [comment]
this appears no-longer-relevant
