### ISSUE TITLE
matrix integration builds

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#5]
jdks(6/7/8/9) \* platforms(win/linux) \* build params(checkinit/rangepos/genbcode)

**Comment by SethTisue** [comment]
JDK version matrix landed at https://github.com/scala/scala/pull/9579

Windows moved to GitHub Actions at https://github.com/scala/scala/pull/9591

the idea of doing regular runs with different params enabled has always been in the back of our minds; we don't need a forever-open ticket on it
