### ISSUE TITLE
refactor conversion from chef attributes to jenkins environment variables

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#60]
Right now, we don't set any global variables, but every worker node does pull in some shared values. This is awkward, because chef-client needs to run on every node when changing a "global" jenkins variable. Instead, we should have a `{ "jenkins": { "environment": { .... } } }` attribute set for every node. On the master node, this is translated into the global env vars for the jenkins master config, whereas for the workers it would go into the jenkins slave config.

**Comment by SethTisue** [comment]
we're just manually managing Jenkins these days and if it died we'd go GitHub Actions rather than bring it back to life
