### ISSUE TITLE
intelligently clean workspace of community build

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#86]
It grows by 2.5GB per run, but we don't want to start from scratch every time -- can we just keep the last extractions/clones/builds? I think dbuild has an option for that.

**Comment by adriaanm** [comment]
See https://github.com/scala/community-builds/pull/106 and https://github.com/scala/scala-jenkins-infra/pull/87

**Comment by SethTisue** [comment]
merged
