### ISSUE TITLE
add PR validation to https://github.com/scala/community-builds

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#92]
We should run the community build (on the last commit only) of PRs submitted. Should be a matter of adding a scabot.conf section.

**Comment by SethTisue** [comment]
perhaps this should be triggered by an explicit command, rather than automatically on every PR.

**Comment by SethTisue** [comment]
closely related: #8

**Comment by SethTisue** [comment]
I'm more and more tempted to tackle this

**Comment by adriaanm** [comment]
We could use the integrate-main flow for this. It can be configured to do a minimal bootstrap using jenkins params and then trigger a community build. I guess we could also just use a fixed Scala version since we're validating the community build here, not the compiler.

**Comment by SethTisue** [comment]
not worth doing on Jenkins. if we move the community build to GitHub Actions, I could maybe get interested again. but as long as the community build is basically a one man show, some kind of automation just aren't worth the trouble
